### ISSUE TITLE
Bug: incorrect configuration file created (at least under Windows)

### ISSUE THREAD

**Issue by engelhro** [nikhil1raghav/kindle-send#13]
I'm using kindle-send version `1.0.2` under Windows. When no configuration file exists, one is created after the necessary information have been requested from the user.

Problem: the SMTP server address given doesn't make it into the configuration file. Instead, the server port is written *twice*, once into the "port" key (as expected) and once into the "server" key (which is **incorrect**).

**Comment by nikhil1raghav** [comment]
Fixed in [v1.0.3-rc-1](https://github.com/nikhil1raghav/kindle-send/releases/tag/v1.0.3-rc-1)
