### ISSUE TITLE
Unusual SMTP port referenced

### ISSUE THREAD

**Issue by engelhro** [nikhil1raghav/kindle-send#14]
I'm using kindle-send version `1.0.2` under Windows.

When the initial pieces of information are requested from the user, the SMTP port is described with the words "usually 587 or 485".

This is a little bit misleading – the usual ports are 587 or 4**6**5 (not 4**8**5)… Please subtract a 20 here :wink:

**Comment by nikhil1raghav** [comment]
Sure, slipped in by mistake. Thanks for pointing out. Will fix it with this #13

**Comment by nikhil1raghav** [comment]
Fixed in this [pre-release](https://github.com/nikhil1raghav/kindle-send/releases/tag/v1.0.3-rc-1)
