### ISSUE TITLE
Feat : Allow to save epubs without sending them

### ISSUE THREAD

**Issue by nikhil1raghav** [nikhil1raghav/kindle-send#15]
**Is your feature request related to a problem? Please describe.**
Sometimes I may want to just store the epub locally, and copy it manually later on.

**Describe the solution you'd like**
A `--dry-run` flag that will save the epub and doesn't send the email

**Comment by volkerwestphal** [comment]
I already had the situation that the generated .epub file was too large to be sent by my email provider (Gmail allows 25MB). A `--dry-run`  would allow scripts to catch this.
