### ISSUE TITLE
Confusing help for option usage

### ISSUE THREAD

**Issue by engelhro** [nikhil1raghav/kindle-send#18]
I find the documentation of the various options a little bit confusing:

The README here on Github shows all examples with two hyphens (`--url`, `--title` etc.), whereas the help output of kindle-send only uses one (`-url`, `-title` etc.).

Funny enough, kindle-send accepts both versions…

I would've expected double hyphens with the "long form" of options (e.g. `--url` or `--title`) and single hyphens with their "short form" (something like `-U` for the URL or `-T` for the title). At least that's the usual approach chosen by so many other command line programs.

Additionally it would be nice (but that's a matter of taste and probably worth a separate request?) to have the most common option (I guess providing an URL?) to work without specifying it explicitly, resulting in a "default option":

`kindle-send <URL>` (= one parameter given, but no option)

instead of

`kindle-send --url <URL>`

**Comment by nikhil1raghav** [comment]
Hi, now there is no need for shorthand with latest release. All other flags can be used as shorthand. Refer `kindle-send help` for usage. Closing this issue.
