### ISSUE TITLE
Please provide a ‘-version’ string

### ISSUE THREAD

**Issue by kseistrup** [nikhil1raghav/kindle-send#5]
**Is your feature request related to a problem? Please describe.**

I don't know which version of `kindle-send` is installed, so I don't know whether I should upgrade or not. I also can't tell the author which version I am reporting a bug for.

**Describe the solution you'd like**

A `-version` switch could be all that is needed. E.g.:

```sh
$ kindle-send -version
kindle-send 1.0.1 (2022-09-06)
```

**Comment by nikhil1raghav** [comment]
Thanks for raising this, I'm working on it now. Version string is more important right now, as the main method of distribution is using binaries.

**Comment by nikhil1raghav** [comment]
Will publish a new release with these changes and storing config in `.config`
