### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by Erk-** [nikhil1raghav/kindle-send#8]
**Is your feature request related to a problem? Please describe.**
I am looking into packaging the program for the AUR and I was hoping you could provide a license. Since the status quo with "All rights reserved" is not great in all cases.

**Describe the solution you'd like**
A license file added to the repository

**Comment by nikhil1raghav** [comment]
Hi, thanks for packaging it for arch. I want a suggestion here, will AGPL be good for this purpose?

**Comment by Erk-** [comment]
I think AGPL fits pretty well since I could see people use it as a service in the future
