### ISSUE TITLE
Error when sending web page. Image filename syntax is incorrect.

### ISSUE THREAD

**Issue by CkR-0ff** [nikhil1raghav/kindle-send#9]
**Describe the bug**
When sending a web page an error is thrown on attempted image save. (Looks like the image names are not correctly trimmed before setting then as filename))
At the end of console output it says:

``` powershell
Setting img src from https://www.howtogeek.com/wp-content/uploads/2022/09/gopher.png?trim=1,1&bg-color=000&pad=1,1 to ../images/gopher.png?trim=1,1&bg-color=000&pad=1,1
Setting img src from https://www.howtogeek.com/wp-content/uploads/2022/09/00042.png?trim=1,1&bg-color=000&pad=1,1 to ../images/00042.png?trim=1,1&bg-color=000&pad=1,1
Added 1 articles
unable to create file ce77f557-736c-4bd6-a1f2-1ce0588b73c8\EPUB\images\copy-and-paste.png?trim=1,1&bg-color=000&pad=1,1: open C:\Users\grego\AppData\Local\Temp\ce77f557-736c-4bd6-a1f2-1ce0588b73c8\EPUB\images\copy-and-paste.png?trim=1,1&bg-color=000&pad=1,1: The filename, directory name, or volume label syntax is incorrect.
```

Also at the end the .epub file is generated but with 0 size.

**To Reproduce**
1. Try to do `kindle-send --url "https://www.howtogeek.com/830179/how-to-run-stable-diffusion-on-your-pc-to-generate-ai-images/" --title "Some Title"`
2. See error
3. Check confirm generated file is 0B

**Expected behavior**
Saving the images successfully and continue the process to generate the full .epub file.

**Desktop:**
 - OS: Windows 10 Pro
 - Version 1.0.1
 - Command line tool:  powershell

**Comment by nikhil1raghav** [comment]
Seems like an issue with how Windows handles the filename. 
I was able to send this page using the linux version.


You're right image names should be trimmed correctly to avoid it, as query parameters aren't even needed when file is stored locally.

**Comment by nikhil1raghav** [comment]
Will release these changes today in v1.0.2, need to add a license and an issue with path of config file
